[theme]
base = "light"
primaryColor = "#121216"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f2fb"
textColor = "#111114"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
